### ISSUE TITLE
Icons are not open as binary file on windows

### ISSUE THREAD

**Issue by vosmont** [akbooer/openLuup#1]
Hello akbooer,

on a windows system, icons are not correctly displayed :

`2016-02-26 10:11:02.748   openLuup.server:: new client connection: tcp{client}: 02BEF5B0
2016-02-26 10:11:02.748   openLuup.server:: /icons/iconVSwitch_0.png tcp{client}: 02BEF5B0
2016-02-26 10:11:02.767   openLuup.server:: request completed (5 bytes, 1 chunks, 18 ms) tcp{client}: 02BEF5B0`

it's because in windows, you have to open the files as a binary file, otherwise because of zero bytes, the file will be send partially.
http://www.lua.org/pil/21.2.2.html

It's in "server.lua" at line 123 :
`local f = io.open(path,'rb')`

I have done some tests and it seems to work for the other files (no regression).

Besides, at line 126,
`info = (f: read "*a") or ''`
should perhaps be
`info = (f: read "*all") or ''`
(the two seems to work)

**Comment by akbooer** [comment]
Binary file reads fixed in release 0.7.0 - thanks!

"*a" is fully supported syntax for io.read(), so no change needed there.
