### ISSUE TITLE
luup.variable_set and VeraBridge

### ISSUE THREAD

**Issue by vosmont** [akbooer/openLuup#16]
Hello @akbooer,

it seems that changing device variable, on a distant Vera exposed via VeraBridge has no effect.

luup.variable_set does nothing if device id is above BRIDGEBLOCK.
Could it be possible that in this case VeraBridge update the variable value on the distant Vera ?

Thanks,
vosmont

**Comment by akbooer** [comment]
Not quite clear what you're trying to do here?  All the variable values on a mirrored bridge are updated from the remote Vera's values.  As clearly documented in the User Guide:

> This means that WHATEVER changes you make to cloned device variables will get overwritten frequently. The motto is this...  do NOT write variables to cloned devices.

You should use an appropriate action call if you want to change the value of a remote variable.

**Comment by vosmont** [comment]
I would like to set the initial dim level of a light.
The problem is that the action "SetOnEffectLevel" is not implemented on the legacy Vera.

As explained in the post https://github.com/toggledbits/DelayLight/issues/13, it's possible to do that with the variable "LoadLevelLast" (not documented) (and it works).

But the brain of my Home Automation System is in openLuup : so I need to set this variable from openLuup

et voilà :)

**Comment by akbooer** [comment]
My point is not specifically related to openLuup, or VeraBridge.  It is a general Luup/MiOS principle.  You should not change the value of a variable on a device that is not controlled by your plugin.

All I'm suggesting is that you use an action to do that.  It seems, though, from reading the above that the target device (on legacy Vera) does not implement such an action.

It would be possible to get VeraBridge to do this for you, by implementing an action call to set variables on the remote Vera (and, perhaps, converting any variable_set requests to bridged devices to use that call.)

**Comment by akbooer** [comment]
The latest development commit (v 19.4.10) has a VeraBridge action **RemoteVariableSet** which has the obvious parameters (except that the device number may either be the native number on the remote Vera, or the local one known by openLuup.)

I have yet to work out a strategy to integrate this with luup.variable_set() or the &id=variableset requests, since both the bridge, AltUI, and the openLuup system itself, may need to use those to access the actual variable.

**Comment by vosmont** [comment]
Great it works !
I spent a little time before I realized that I had to delete the file "S_VeraBridge.xml" to get the update.

My openLuup install has now several years :)
Are there other files that I should delete with the new concept of virtual filesystem ?

**Comment by akbooer** [comment]
The cache has been around for a while, but older installs left some files where they shouldn't.  It's not an easy problem to clean up automatically, apart from a clean install (you can, of course, save and restore your user_data.json.)

The virtual file system is also used during clean installs to physically create some files, but generally, any device files that you see in the virtual file manifest should not be needed on your file system.

**Comment by akbooer** [comment]
Happy for me to close this issue, then?

**Comment by vosmont** [comment]
Yes, it's OK.
Thanks !

**Comment by akbooer** [comment]
Issue closed
