### ISSUE TITLE
Some initial install errors.

### ISSUE THREAD

**Issue by BuxtonCalvin** [akbooer/openLuup#17]
Documentation states variable logfile is located in /var/cmh/.  Actual path  is /var/log/cmh.  Perhaps create this folder as part of the install, as well as correcting the documentation.....

Also, ALTUI creates a "zwave" device, and with the initial clean install, the device files do not exist.  One needs to copy the /files/ D_ZWaveNetwork.xml, S_ZWaveNetwork.xml, I_ZWave.xml, and the /icons/zwave_default.png from a Vera?  I found my files in my older openluup installation.

Otherwise, openLuup starts right up!

**Comment by akbooer** [comment]
Thanks for that.  Will take a look at the documentation.

It's openLuup, not AltUI, which creates the ZWaveNetwork device.  The error is not important, but I should suppress it.  It's been there for years!  It does not stop the installation from working.

**Comment by BuxtonCalvin** [comment]
You may also want to auto create the historian directory "cmh-ludl/history" and add the attribute setting to startup lua, as historian is now more or less part of openLuup.  It will make it much easier to get things going.
