### ISSUE TITLE
Scope problems

### ISSUE THREAD

**Issue by BuxtonCalvin** [akbooer/openLuup#18]
Hey AK,

I'm trying to launch a plugin using RigPapas framework, but I keep running into global/nil errors.  Attached is a word doc that shows a snapshot of the openLuup global status, a snapshot of trying to display a value from some of these globals (including the ALTUI global), and some of the implementation file code that creates the globals.  Do you have any idea what's occurring here.
[ScopeError.docx](https://github.com/akbooer/openLuup/files/3512566/ScopeError.docx)

**Comment by akbooer** [comment]
Yes, this is all as expected.  Perhaps the best place for discussion is the Vera forum, rather than here?  However, it turns out that there is really no such thing as a global (that term is something of a misnomer) in Lua, and because openLuup runs in a single Lua instance, it would be a disaster if plugins shared the same global space.

The global scope of Scene Lua, Startup Lua (and Shutdown) and Lua Test are all shared with each other, and the plugins are each separate, but available if you access their global environment correctly.

For example, to access the global environment of device N, you can do this:

`local G = luup.devices[N].environment`

then your device globals will be elements of the table G.

**Comment by BuxtonCalvin** [comment]
Thanks AK, that was a huge! help.  What I found is that if in my **lua file**, I explicitly path my globals declared in the **implementation file** ie in the lua file-- `local foo = luup.devices[5].environment.PFB`, I no longer get the nil error.  However, this does leave the question as to why globals declared in the implementation file are not available to the lua file directly (or the plugin as a whole).  I am also setting `module("L_EchoBridge1", package.seeall)` in the lua file and I tried using the `<files></files>` tag in the implementation file but this did not change the scope of the declared globals either.
So the plugin runs with explicit paths, but that is a real pain.....

As for the forum, no problem with that, I was just a little wary of openLuup topics as regards the new owners as you never know if they see you as a Vera adjunct, or a competitor.....

**Comment by akbooer** [comment]
Ah, then I am not fully understanding what you are trying to do.  Indeed, there should be no reason to invoke the mechanism I described directly, it’s just the way that openLuup works under the covers.  Its aim, after all, is to emulate to a great extent  the Vera environment.  You should not have to do anything different.

What **exactly** are you doing?  I need to see the the implementation file, at the very least, and a relevant segment of the Lua file.  The module statement is ignored in openLuup .lua files.  You are aware that the order of the functions and files tags in the implementation file is significant. 

New Vera management is fine with openLuup.  I have, after all, helped in a few ways to keep people with their platform.

**Comment by BuxtonCalvin** [comment]
> What exactly are you doing? 
I'm writing a plugin, using RigPapa's Vera framework. The plugin interfaces with the HomeAssistant API.  Specifically, the plugin uses an http post to send a URL, with a JSON payload, that triggers the Amazon Alexa echo device to announce the phrase that is sent in the JSON payload.

I've been at this for awhile, and it was only after using your hard path syntax that I confirmed that the underlying problem in getting the plugin running was a scope issue.  I'm going to attach the plugin files.  The plugin launches, and you can see the basics of what I'm up to, but I still need to debug the use of service variables in my function calls.  The relationship between the service definitions and variables, and the lua code in the .lua file is more or less as clear as mud to me, but I'm getting there.

Anyway, any place where you see `luup.devices[5].environment.`  is a hard code to the PFB configuration table that is created in the implementation file.

[EchoHomeAssistantBridge.zip](https://github.com/akbooer/openLuup/files/3513767/EchoHomeAssistantBridge.zip)

**Comment by akbooer** [comment]
- you don't have a `<files>` tag in your implementation file
- there is a syntax error around line 37 in your .json file

The first point above is probably your difficulty with globals.  You should not need to do anything with the device number or its environment.

**Comment by BuxtonCalvin** [comment]
Hey AK. First, thanks for the JSON catch.  That would of been hard to find.

I originally removed the `<files>` tag because it did not seem to make a difference.  It is now back in the Implementation file. I re-edited most of the files today and have gotten the plugin to run with two exceptions:  1 I still have to hard code the device path.  I have tried every which way to reorder the tags in the implementation file. but nothing seems to work except a hard code.  Could you load my plugin (attached) and take a look please.
2, the  `['Authorization` : Bearer'] = HomeAssistantToken`  header does not seem to work in openLuup.  I am able to get a good response from the linux command line with the commented curl command that you can see in the lua file (using http, not https) but I get a 401 error on the return when I try to use a "post" through openLuup.  Do you support this type of header.
[EchoHomeAssistantBridge.zip](https://github.com/akbooer/openLuup/files/3518614/EchoHomeAssistantBridge.zip)

Advise as always greatly appreciated.

**Comment by akbooer** [comment]
closed, because this is not really an openLuup issue.
