### ISSUE TITLE
Question: Hubitat interface

### ISSUE THREAD

**Issue by RHCPNG** [akbooer/openLuup#22]
Hi akbooer,

I'm evaluating moving away from Vera, but want to keep using Openluup. Is there a plugin to interface the Hubitat with openluup? Or are you maybe considering this?

Thanks.

Regards,

Niels

**Comment by akbooer** [comment]
My move recently has been towards Shelly devices (ie. direct WiFi control with HTTP.)  However, you're likely to find some good answers at [Smarthome.Community](http://smarthome.community) – see you there!
