### ISSUE TITLE
Still use it, still love it..

### ISSUE THREAD

**Issue by nodecentral** [akbooer/openLuup#29]
Hi @akbooer 

Hope all is well, just wondering if you had any more updates planned for openLuup.?

**Comment by akbooer** [comment]
Thanks for that.  I still use it and love it too.  In fact, it's central to my HA system, especially for Shelly devices and data logging.

My latest project is adding a Prolog logic engine to the system, as discussed on the forum at [Smarthome community](https://smarthome.community/).  This is a fairly open-ended project and is taking a lot of my time.  

If you have anything in particular development for openLuup in mind, you are best asking there.  It does just about everything I need right now (aside from the logic engine) so no need for frequent updates.
