### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by sle118** [akbooer/openLuup#3]
This is not an issue.

I wanted to thank you publicly for  this amazing emulator. A few years ago, some time before you decided to write dataYours, I had tried writing my own plugins but the lack of a proper development environment was to much of a barrier for me; I don't like spending most of the time restarting and waiting and reading logs.

I just installed an Ubuntu VM with Lua and eclipse ldt, and I'm back on creating plugins. I grabbed the PioneerRemote code from mios to add status monitoring and possibly a nicer UI. The goal is to have lights turn on when muting my home theater amplifier and to turn them back off when unmuting. It takes quite a bit of efforts to be lazy in the automation world ;)

So thanks again; openluup will allow more plugins to be developed I'm sure!

**Comment by akbooer** [comment]
Much appreciate... glad it helps...

...I've marked the "issue" as "won't fix", since it's not broken!

**Comment by akbooer** [comment]
Hope it’s still working for you!  Things have come on a long way since you raised this!
