### ISSUE TITLE
No ability to add a new Scene via the Console UI

### ISSUE THREAD

**Issue by nodecentral** [akbooer/openLuup#32]
Hi @akbooer 

As someone who greatly prefers your Console view over ALTUI, just an FYI to say, there is not a button/option (at least not one I could find ?) to create a new scene?

Also the scenes tiles are not responsive to the screen, so they run continuously off to the right…

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/c46620de-0503-49fe-a778-e0fd2996b8e4">

**Comment by akbooer** [comment]
All the tiles wrap correctly on my machines.  Are you sure that's a full-screen snapshot?

Looks like you are running a rather out of date version (the little word MODAL at the bottom hails from an old test version.) Suggest you update to the latest development version.

For a new scene, try the **+Create** button on the Tables > scenes_table page...

<img width="730" alt="Screenshot 2024-11-03 at 12 27 15" src="https://github.com/user-attachments/assets/8a50361e-297e-4dbd-a649-a32c43c357c5">

**Comment by nodecentral** [comment]
Thanks, for pointing me to the Tables for the **+Create** option, when it comes to getting the latest `development version`

How/where do I get that from, I had updated recently from an earlier exchange we had..

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/32142b03-adc1-46d0-a589-2991fe2aa1fa">

**Comment by akbooer** [comment]
Type **development** into the box next to openLuup and then click on the blue icon with arrows.  Takes about 15 seconds before it reloads. 

This sort of support is much better given on the smarthome forum rather than GitHub.

**Comment by nodecentral** [comment]
Thanks, updated to the Development version, however it’s still not acting responsive 

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/d35ee3c9-be5f-40de-bc9f-fef140e1b836">

And if i try a more mobile view, it’s like this..

<img width="432" alt="image" src="https://github.com/user-attachments/assets/d38c4f08-dab5-4c72-92c3-91544858b2a7">

Tiles do not seem to adjust for me.. (I’m an Apple iPad / iPhone (Safari user) )

**Comment by akbooer** [comment]
Don't know what to say.  I use it on an iPad all the time and it adjusts itself to a rotated screen.  It was never designed to be a responsive layout for an iPhone.

The openLuup console is not, in any case, meant to be a slick user interface.  It is a configuration and status tool, not in any way a replacement for AltUI.

My main interface to my system these days is the Apple Home app.

**Comment by nodecentral** [comment]
> The openLuup console is not, in any case, meant to be a slick user interface. It is a configuration and status tool, not in any way a replacement for AltUI.

I totally get it, it’s just that I love the simplicity of what you have created 🥳 - sorry for flagging these types of things.

ALTUI is OK, but it’s not as clean and tidy as what you have built with the Console. (Give yourself some credit, Console does what I need, and I’m only spending a lot of time in it at the moment as I’m setting things up, but once done - i won’t need to go in anywhere near as much, if at all.
