### ISSUE TITLE
Beaglebone Documentation

### ISSUE THREAD

**Issue by OuzoDuoTres** [akbooer/openLuup#4]
Suggested changes:
1) pg 4 Debian (Beaglebone Black)...I found it necessary do to and apt-get update before these packages would install properly
2) pg 5 Openluup Instalation:  
* the wget hyperlink underline obscures the fact that the file is openLuup_install.exe.  Shouldn't be a problem for anyone paying attentions. I wasn't.
* the command line lua5.1 openLuup_install should have .lua appended to the file name, at least it would not run on my machine without it

With these changes I was able to get everything installed and access AltUI through the web URL. 

Thanks!

**Comment by akbooer** [comment]
1. ALWAYS a good plan to do an update before an install.
2. I'll check, but believe you're right about the .lua

Will clarify documentation next update.

Thanks, AK

**Comment by akbooer** [comment]
Documents update in development branch 2017.04.26
