### ISSUE TITLE
beaglebone Install Linking to Vera

### ISSUE THREAD

**Issue by OuzoDuoTres** [akbooer/openLuup#5]
Also followed the instructions on page 7, "linking to vera". simply checking VeraBridge Update did not appear to install the plug-in, at least it did not appear in the devices page after an inordinate wait time.  Also attempted a reload Luup engine, VeraBridge did not appear in the devices window.

**Comment by OuzoDuoTres** [comment]
Ok, fixed it.  I would suggest on page 7 you make a distinction between clicking on the VeraBridge Update check box and the Update Now button.  What worked for me was checking the box and then hitting the update now button.  Simply checking the box, or checking the box and waiting or waiting until later and hitting the reload Luup did not install the plugin.  I guess I just have more to learn about how these plugins really install.

**Comment by akbooer** [comment]
Yes, you have stumbled across the right modality for this interface.  That's the way it's supposed to work.  I'll try and clarify the documentation on the next revision.
