### ISSUE TITLE
error in callback [lr_ALTUI_Handler] ......

### ISSUE THREAD

**Issue by nodecentral** [akbooer/openLuup#9]
Hi @akbooer 

I’ve followed the guide on a Debian VM I have, creating the required folder cmh-ludl/ in my home directory and then running lua5.1 openLuup_install.lua but  when accessing the new url - I receive the following error message

error in callback [lr_ALTUI_Handler] : [string "L_ALTUI.lua"]:2306: attempt to index local 'tbl' (a nil value)

Any ideas ?

**Comment by akbooer** [comment]
It seems to be an AltUI issue.  Described and resolved here
[http://forum.micasaverde.com/index.php/topic,83034.0.html](url)
